mod exti;
mod fast_pin;
mod pin;
mod port;

pub use exti::*;
pub use fast_pin::*;
pub use pin::*;
pub use port::*;

pub use crate::ll_api::PinNum;
pub use crate::ll_api::PortNum;
pub use embassy_hal_internal::{Peri, PeripheralType};

#[allow(unused)]
#[macro_export]
macro_rules! foreach_pin {
	($($pat:tt => $code:tt;)*) => {
		macro_rules! __foreach_pin_inner {
			$(($pat) => $code;)*
			($_:tt) => {}
		}
		__foreach_pin_inner!((PA0, 0, 0));
		__foreach_pin_inner!((PA1, 0, 1));
		__foreach_pin_inner!((PA2, 0, 2));
		__foreach_pin_inner!((PA3, 0, 3));
		__foreach_pin_inner!((PA4, 0, 4));
		__foreach_pin_inner!((PA5, 0, 5));
		__foreach_pin_inner!((PA6, 0, 6));
		__foreach_pin_inner!((PA7, 0, 7));
		__foreach_pin_inner!((PA8, 0, 8));
		__foreach_pin_inner!((PA9, 0, 9));
		__foreach_pin_inner!((PA10,0,10));
		__foreach_pin_inner!((PA11,0,11));
		__foreach_pin_inner!((PA12,0,12));
		__foreach_pin_inner!((PA13,0,13));
		__foreach_pin_inner!((PA14,0,14));
		__foreach_pin_inner!((PA15,0,15));
		__foreach_pin_inner!((PB0, 1, 0));
		__foreach_pin_inner!((PB1, 1, 1));
		__foreach_pin_inner!((PB2, 1, 2));
		__foreach_pin_inner!((PB3, 1, 3));
		__foreach_pin_inner!((PB4, 1, 4));
		__foreach_pin_inner!((PB5, 1, 5));
		__foreach_pin_inner!((PB6, 1, 6));
		__foreach_pin_inner!((PB7, 1, 7));
		__foreach_pin_inner!((PB8, 1, 8));
		__foreach_pin_inner!((PB9, 1, 9));
		__foreach_pin_inner!((PB10,1,10));
		__foreach_pin_inner!((PB11,1,11));
		__foreach_pin_inner!((PB12,1,12));
        __foreach_pin_inner!((PB13,1,13));
        __foreach_pin_inner!((PB14,1,14));
        __foreach_pin_inner!((PB15,1,15));
        __foreach_pin_inner!((PC0, 2, 0));
        __foreach_pin_inner!((PC1, 2, 1));
        __foreach_pin_inner!((PC2, 2, 2));
        __foreach_pin_inner!((PC3, 2, 3));
        __foreach_pin_inner!((PC4, 2, 4));
        __foreach_pin_inner!((PC5, 2, 5));
        __foreach_pin_inner!((PC6, 2, 6));
        __foreach_pin_inner!((PC7, 2, 7));
        __foreach_pin_inner!((PC8, 2, 8));
        __foreach_pin_inner!((PC9, 2, 9));
        __foreach_pin_inner!((PC10,2,10));
        __foreach_pin_inner!((PC11,2,11));
        __foreach_pin_inner!((PC12,2,12));
        __foreach_pin_inner!((PC13,2,13));
        __foreach_pin_inner!((PC14,2,14));
        __foreach_pin_inner!((PC15,2,15));
        __foreach_pin_inner!((PD0, 3, 0));
        __foreach_pin_inner!((PD1, 3, 1));
        __foreach_pin_inner!((PD2, 3, 2));
        __foreach_pin_inner!((PD3, 3, 3));
        __foreach_pin_inner!((PD4, 3, 4));
        __foreach_pin_inner!((PD5, 3, 5));
        __foreach_pin_inner!((PD6, 3, 6));
        __foreach_pin_inner!((PD7, 3, 7));
        __foreach_pin_inner!((PD8, 3, 8));
        __foreach_pin_inner!((PD9, 3, 9));
        __foreach_pin_inner!((PD10,3,10));
        __foreach_pin_inner!((PD11,3,11));
        __foreach_pin_inner!((PD12,3,12));
        __foreach_pin_inner!((PD13,3,13));
        __foreach_pin_inner!((PD14,3,14));
        __foreach_pin_inner!((PD15,3,15));
        __foreach_pin_inner!((PE0, 4, 0));
        __foreach_pin_inner!((PE1, 4, 1));
        __foreach_pin_inner!((PE2, 4, 2));
        __foreach_pin_inner!((PE3, 4, 3));
        __foreach_pin_inner!((PE4, 4, 4));
        __foreach_pin_inner!((PE5, 4, 5));
        __foreach_pin_inner!((PE6, 4, 6));
        __foreach_pin_inner!((PE7, 4, 7));
        __foreach_pin_inner!((PE8, 4, 8));
        __foreach_pin_inner!((PE9, 4, 9));
        __foreach_pin_inner!((PE10,4,10));
        __foreach_pin_inner!((PE11,4,11));
        __foreach_pin_inner!((PE12,4,12));
        __foreach_pin_inner!((PE13,4,13));
        __foreach_pin_inner!((PE14,4,14));
        __foreach_pin_inner!((PE15,4,15));
        __foreach_pin_inner!((PF0, 5, 0));
        __foreach_pin_inner!((PF1, 5, 1));
        __foreach_pin_inner!((PF2, 5, 2));
        __foreach_pin_inner!((PF3, 5, 3));
        __foreach_pin_inner!((PF4, 5, 4));
        __foreach_pin_inner!((PF5, 5, 5));
        __foreach_pin_inner!((PF6, 5, 6));
        __foreach_pin_inner!((PF7, 5, 7));
        __foreach_pin_inner!((PF8, 5, 8));
        __foreach_pin_inner!((PF9, 5, 9));
        __foreach_pin_inner!((PF10,5,10));
        __foreach_pin_inner!((PF11,5,11));
        __foreach_pin_inner!((PF12,5,12));
        __foreach_pin_inner!((PF13,5,13));
        __foreach_pin_inner!((PF14,5,14));
        __foreach_pin_inner!((PF15,5,15));
        __foreach_pin_inner!((PG0, 6, 0));
        __foreach_pin_inner!((PG1, 6, 1));
        __foreach_pin_inner!((PG2, 6, 2));
        __foreach_pin_inner!((PG3, 6, 3));
        __foreach_pin_inner!((PG4, 6, 4));
        __foreach_pin_inner!((PG5, 6, 5));
        __foreach_pin_inner!((PG6, 6, 6));
        __foreach_pin_inner!((PG7, 6, 7));
        __foreach_pin_inner!((PG8, 6, 8));
        __foreach_pin_inner!((PG9, 6, 9));
        __foreach_pin_inner!((PG10,6,10));
        __foreach_pin_inner!((PG11,6,11));
        __foreach_pin_inner!((PG12,6,12));
        __foreach_pin_inner!((PG13,6,13));
        __foreach_pin_inner!((PG14,6,14));
        __foreach_pin_inner!((PG15,6,15));
        __foreach_pin_inner!((PH0, 7, 0));
        __foreach_pin_inner!((PH1, 7, 1));
        __foreach_pin_inner!((PH2, 7, 2));
        __foreach_pin_inner!((PH3, 7, 3));
        __foreach_pin_inner!((PH4, 7, 4));
        __foreach_pin_inner!((PH5, 7, 5));
        __foreach_pin_inner!((PH6, 7, 6));
        __foreach_pin_inner!((PH7, 7, 7));
        __foreach_pin_inner!((PH8, 7, 8));
        __foreach_pin_inner!((PH9, 7, 9));
        __foreach_pin_inner!((PH10,7,10));
        __foreach_pin_inner!((PH11,7,11));
        __foreach_pin_inner!((PH12,7,12));
        __foreach_pin_inner!((PH13,7,13));
        __foreach_pin_inner!((PH14,7,14));
        __foreach_pin_inner!((PH15,7,15));
	};
}
