[package]
name = "ll_bind_ch32v20x"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = { version = "1.2.0", features = ["restore-state-u8"]}

[build-dependencies]
cc = "1.2"
bindgen = "0.72.1"
walkdir = "2.5.0"


